---
title: "NESN 360 Monthly Subscriber Report - January 2024"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#E3E9EF"
      fg: "#132746" 
      primary: "#D5FA2C"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

```{r setup2, include=F, message = F, warning = F}
library(tidyverse)
library(lubridate)
library(gt)

df_s <- read_csv('subscriptions_2024_02_01.csv') #CHANGE HERE
roku <- read_csv('roku_subscriptions_2024_02_01.csv') %>% #CHANGE HERE
  filter(sub_start_date >= mdy('1/17/23')) %>% 
  filter(!is.na(email))

df <- df_s %>% 
  full_join(roku) %>% 
  mutate(sdc = ifelse(sub_start_date == canceled_at, 1, 0))

wk_no <- 5 # CHANGE HERE
wk_no_off <- 5  # CHANGE HERE
wk_range <- c(mdy('01/28/24'):mdy('02/03/24')) # CHANGE HERE
wk_end_epi <- mdy('02/03/24') # CHANGE HERE

cancel <- df %>% 
  filter(!is.na(canceled_at)) %>% 
  count(canceled_at) %>% 
  mutate(month = month(canceled_at, label = T, abbr = F)) 


churn <- df %>% 
  filter(!is.na(churn_date)) %>% 
  count(churn_date) %>% 
  mutate(month = month(churn_date, label = T, abbr = F)) 


subs <- df %>% 
  count(sub_start_date) %>% 
  mutate(month = month(sub_start_date, label = T, abbr = F)) %>% 
  filter(sub_start_date != today())


churn_2 <- churn %>% 
  select(-month) %>% 
  rename(churns = n)

cancel_2 <- cancel %>% 
  select(-month) %>% 
  rename(cancels = n )

sdc <- df %>% 
  group_by(sub_start_date) %>% 
  summarise(sdc = sum(sdc, na.rm = T))

  
subs_2 <- df %>%
  count(sub_start_date) %>%
  mutate(date = sub_start_date,
         month = month(date, label = T, abbr = F),
         total_subs = cumsum(n)) %>% 
  select(-sub_start_date) %>% 
  rename(subscriptions = n) %>% 
  relocate(date) %>% 
  full_join(churn_2, by = c('date' = 'churn_date')) %>% 
  full_join(cancel_2, by = c('date' = 'canceled_at')) %>%
  full_join(sdc, by = c('date' = 'sub_start_date')) %>% 
  mutate(churns = ifelse(is.na(churns),0,churns),
         cancels = ifelse(is.na(cancels),0,cancels),
         sdc = ifelse(is.na(sdc),0, sdc),
         total_churns = cumsum(churns),
         active_subs = total_subs - total_churns,
         churn_pct = churns/active_subs,
         cancel_pct = cancels/active_subs,
         subs_pct = subscriptions/active_subs) %>% 
  filter(date != today() & date >= mdy('6/1/2022')) %>% 
  mutate(weekday = weekdays(date),
         .after = month)

subs_2 <- subs_2 %>% 
  filter(date <= wk_end_epi) %>% 
  mutate(wk_no = epiweek(date),
         year = year(date),
         subs_rank = rank(desc(subscriptions),
                          ties.method = 'last'),
         churn_rank = rank(desc(churns),
                          ties.method = 'last'),
         cancel_rank = rank(desc(cancels),
                          ties.method = 'last'))
  

asdf <- subs_2 %>%
  group_by(epiyear(date), wk_no) %>%
  summarise(subs = sum(subscriptions),
            churns = sum(churns),
            cancels = sum(cancels),
            sdc = sum(sdc),
            wk_start = min(date),
            wk_end = max(date)) %>% 
  rename(year = 1) %>% 
  arrange(year, wk_no) %>% 
  ungroup() %>% 
  filter(wk_start <= wk_end_epi) %>% 
  mutate(net_subs = subs - churns,
         subs_rank = rank(desc(subs),ties.method = 'last'),
         churn_rank = rank(desc(churns), ties.method = 'last'),
         cancel_rank = rank(desc(cancels), ties.method = 'last'))
```


Column {data-width=666 .tabset}
-----------------------------------------------------------------------

### Net Subscribers

```{r, fig.asp = .5}
my <- "January 2024"

net_subs_plot <- subs_2 %>% 
  filter(year(date) == 2024 & month(date) == 1) %>% 
  mutate(net_subs = subscriptions - churns,
         net_col = ifelse(net_subs >=0, '#08a312', '#e3160b')) %>% 
  ggplot(aes(date, net_subs, fill = net_col,
             text = paste0(subscriptions, " Subscriptions, ", churns, " Churns"))) +
  geom_col() +
  scale_fill_identity()+
  theme_minimal()  +
  guides(fill = 'none') +
  labs(x = '',
       y = 'Net Subscribers',
       title = "January 2024 - Net NESN 360 Subscribers by day") +
  theme(panel.grid.minor = element_blank(),
        plot.title.position = 'plot',
        plot.title = element_text(face = 'bold', size = 11))

plotly::ggplotly(net_subs_plot, tooltip = c('x','y', 'text'))
```

### Active Subscribers

```{r, fig.asp=.5}
active_subs_plot <- subs_2 %>% 
  filter(year(date) == 2024 & month(date) == 1) %>% 
  ggplot(aes(date, active_subs)) +
  geom_point() +
  geom_line()+
  theme_minimal()  +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 6),
                     labels = scales::comma) +
  labs(x = '',
       y = 'Active Subscribers',
       title = "January 2024 - Active NESN 360 Subscribers by day") +
  theme(panel.grid.minor = element_blank(),
        plot.title.position = 'plot',
        plot.title = element_text(face = 'bold', size = 11))

plotly::ggplotly(active_subs_plot)
```

Column {data-width=334}
-----------------------------------------------------------------------

### Weekly KPIs


```{r, fig.asp = .6}
test_tab <- asdf %>% 
  filter(year == 2024 & month(wk_end) == 1) %>% 
  select(wk_no, wk_start, wk_end, net_subs, subs, churns, cancels) %>% 
  gt(rowname_col = 'wk_no') %>% 
  gtExtras::gt_theme_538() %>% 
  fmt_date(columns = 2:3, date_style = 10) %>% 
  fmt_number(columns = 4:7, decimals = 0) %>% 
  tab_header(title = 'NESN 360 - Weekly Subscriber KPIs',
             subtitle = glue::glue('January 2024')) %>% 
  tab_options(heading.title.font.weight = 'bold') %>% 
  cols_label(
    wk_start = "Start",
    wk_end = "End",
    net_subs = "Net Subs"
  ) %>% 
  opt_row_striping() %>% 
  opt_table_font(
    font = list(
      google_font(name = "Lexend"),
      "Cochin", "Serif"
    )
  ) %>% 
  grand_summary_rows(
    columns = c(4,5,6,7),
    fns = list(Total = ~sum(.)),
    fmt = ~fmt_number(.,decimals = 0))

test_tab
```

### Pending Monthly Cancelations

```{r}
pending <- df %>% 
  filter(status == 'active') %>% 
  filter(plan == 'month') %>% 
  filter(cancel_at_period_end == T) %>% 
  count(expiration_date)

tot_pend <- scales::comma(sum(pending$n))
tm1 <- lubridate::today()

pending_plot <- pending %>% 
  filter(expiration_date >= (today() - days(2))) %>% 
  ggplot(aes(expiration_date, n)) +
  geom_col(fill = '#fc4e03', alpha = 0.77) +
  scale_y_continuous(expand = c(0,1),
                     breaks = scales::pretty_breaks(n = 5))+
  theme_minimal() +
  theme(legend.position = 'none',
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.title.position = 'plot',
        plot.title = element_text(face = 'bold', size = 11),
        plot.subtitle = element_text(face = 'italic', size = 9)) +
  labs(x = 'Expiration Date',
       y = 'Expiring Subscriptions',
       title = glue::glue("{tot_pend} Pending Cancelations as of {tm1}"))

plotly::ggplotly(pending_plot)

```

